language: cpp
dist: xenial
addons:
  apt:
    sources:
      - llvm-toolchain-xenial-6.0
    packages:
      - clang-6.0
  homebrew:
    brewfile: true
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
env:
  global: PATH="/usr/local/opt/llvm/bin:/usr/lib/llvm-6.0/bin/:$PATH"
script: make test
