language: cpp
dist: xenial
addons:
  apt:
    sources:
      - llvm-toolchain-xenial-6.0
    packages:
      - clang-6.0
  homebrew:
    brewfile: true
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
env:
  global:
    - PATH="/usr/local/opt/llvm/bin:/usr/lib/llvm-6.0/bin/:$PATH"
    - LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
    - CPPFLAGS="-I/usr/local/opt/llvm/include"
script:
  - clang --version
  - make test
